name: Build and Push Obsidian-OS
'on':
  schedule:
    - cron: '0 0 * * 1'  # Weekly on Mondays
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: obsidian-os
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  push-ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout Push to GHCR
        uses: actions/checkout@v4

      - name: Free Disk Space (Ubuntu)
        run: |
          echo "Freeing disk space..."
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/share/swift
          sudo docker image prune --all --force
          df -h

      - name: Lowercase Registry Owner
        id: registry_case
        run: |
          echo "registry=${IMAGE_REGISTRY,,}" >> $GITHUB_OUTPUT

      - name: Generate Tags
        id: generate_tags
        shell: bash
        run: |
          TIMESTAMP=$(date +%Y%m%d)
          SHA_SHORT=$(git rev-parse --short HEAD)
          TAGS="latest ${TIMESTAMP} ${SHA_SHORT}"
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT

      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            ./Containerfile
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ steps.generate_tags.outputs.tags }}
          oci: true

      - name: Log in to GHCR
        id: push
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ steps.registry_case.outputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Sign container image
        uses: sigstore/cosign-installer@v3.5.0
        with:
          cosign-release: 'v2.2.4'

      - name: Sign the images
        run: |
          cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ steps.registry_case.outputs.registry }}/${{ env.IMAGE_NAME }}@${{ steps.push.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
